project:
  type: website

website:
  title: "datapages"
  page-footer:
    background: light
    left: |
      Datapages is built by [Mika Braginsky](https://mikabr.io/) and [Mike Frank](https://web.stanford.edu/~mcfrank/) at Stanford University and licensed under [GNU GPL v3](https://github.com/datapages/datapage/tree/main?tab=GPL-3.0-1-ov-file).
    right: 
      - icon: github
        href: https://github.com/datapages/datapages.github.io

format:
  html:
    title-block-banner: var(--bs-primary)
    title-block-banner-color: var(--bs-light)
    theme: [cosmo, theme.scss]
    mainfont: Nunito Sans
    fontsize: 1rem
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
